name: Github Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  delete:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " wow: ${{ github.event_name}}"
      -uses: actions/checkout@v3.3.0

      -

  
  


  
 
    
